# CI jobs

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nina:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: build
      run: docker run --rm -v $PWD:/module simatai/espidf:3.3.1 /bin/bash -c "cd NINA/firmware; make clean; make all;"
    
    - name: store-nina-build
      uses: actions/upload-artifact@v2
      with:
        name: nina-firmware
        path: |
              build/*.bin
              build/bootloader/bootloader.bin
              build/*.elf
              build/*.map
